version: '3.0'

expectations:
  population_size: 1000

actions:

# Asthma indicator (AST007) actions

  generate_study_population_ast007:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_ast007 
      --index-date-range "2019-01-01 to 2022-03-31 by month" 
      --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ast007*.csv
 
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity 
      --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

  join_ethnicity_ast007:
    run: >
      cohort-joiner:v0.0.46 
        --lhs output/input_ast007*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ast007]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ast007*.csv

  generate_measures_ast007:
      run: cohortextractor:latest generate_measures 
        --study-definition study_definition_ast007 
        --output-dir=output/joined
      needs: [generate_study_population_ast007, generate_study_population_ethnicity, join_ethnicity_ast007]
      outputs:
        moderately_sensitive:
          measure_csv: output/joined/measure_*_rate.csv

  calculate_rates_ast007:
      run: python:latest python analysis/rate_calculations_ast007.py
      needs: [join_ethnicity_ast007, generate_measures_ast007]
      outputs:
        moderately_sensitive:
          tables: output/rate_table_*.csv
          plots: output/plot_*.png
          decile_chart: output/decile_chart.png

  # generate_notebook_ast007:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/qof_notebook_ast007.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [calculate_rates_ast007]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/qof_notebook_ast007.html


# Testing Asthma variables
  # generate_study_population_ast007_test_variables:
  #   run: cohortextractor:latest generate_cohort 
  #       --study-definition study_definition_ast007_test_variables 
  #       --index-date-range "2018-03-01 to 2020-03-31 by month" 
  #       --output-dir=output/test
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/test/input_ast007_test*.csv

  # generate_measures_ast007_test:
  #     run: cohortextractor:latest generate_measures 
  #       --study-definition study_definition_ast007_test_variables 
  #       --output-dir=output/test
  #     needs: [generate_study_population_ast007_test_variables]
  #     outputs:
  #       moderately_sensitive:
  #         measure_csv: output/test/measure_*_rate.csv
  
 # Check with separate analysis script 
  # check_data:
  #   run: r:latest analysis/indicator_dates_testing.py
  #   outputs:
  #     moderately_sensitive:
  #       table_csv: output/test/test.csv